name: Call a reusable workflow a

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: Agile-visualizer-Team/TestRepo/.github/workflows/workflow-B.yml@develop
    with:
      config-path: .github/labeler.yml
      test: "CIAO"
        