name : Delete all files from a folder
run-name: Deleting all files from a folder
on:
  schedule: 
  - cron: '0 5,17 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Deleting all files form esame
        run: ls