name: Publish in Artifact Repository Releasable
run-name: Checking if acceptance tests pass
on: 
  workflow_dispatch:

jobs:
  build:
    # Testing
    uses: Agile-visualizer-Team/VsCode-Extension-Acceptance/.github/workflows/tests.yml@main
    secrets:  inherit

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    # Publishing on JFrog
      - run: npm publish --registry https://agilevisualizerteam.jfrog.io/artifactory/api/npm/avs_node_modules/ avs_node_modules/visualizer-asp/