name: publish on Marketplace Visual Studio Code
run-name: publishing a new version on Marketplace Visual Studio Code
on: 
  schedule:
   - cron:  '0 0 1,14 * *'
  workflow_dispatch:

jobs:

  publish-vsm:
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      JFROG_TOKEN: ${{secrets.JFROG_TOKEN}}
      VSCODE_TOKEN: ${{secrets.VSCODE_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install latest version
        run: |
          npm install @agilevisualizerteam/visualizer-asp@latest
          npm install -g @vscode/vsce
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: change name project
        run: ./change_name_organization_package.py node_modules/@agilevisualizerteam/visualizer-asp/package.json visualizer-asp
      # Publishing on Visual Studio Code Marketplace Place
      - name: mv project
        run: | 
          mv node_modules/@agilevisualizerteam/visualizer-asp/ ~
      - name: build
        run: |
          cd ~/visualizer-asp
          ./install.sh
          ./compile.sh
      - name: publish on VSC MP
        run: |
          cd ~/visualizer-asp
          vsce publish -p ${VSCODE_TOKEN}