name: publish in Artifact Repository Releasable
run-name: publishing a new version
on: 
  schedule:
   - cron:  '0 5,17 * * *'
  workflow_dispatch:

jobs:
  build:
    # Testing
    uses: Agile-visualizer-Team/VsCode-Extension-Acceptance/.github/workflows/tests.yml@main
    secrets:  inherit

  publish-gpr:
    needs: build
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm install @agile-visualizer-team/visualizer-asp@latest
          npm install
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: change name project
        run: ./change_name_organization_package.py node_modules/@agile-visualizer-team/visualizer-asp/package.json
      - name: check files
        run: ls -a /home/runner/work/VsCode-Extension-Acceptance/VsCode-Extension-Acceptance/node_modules/@agile-visualizer-team
    # Publishing on JFrog
      - name: publish on JFrog
        run: npm publish node_modules/@agile-visualizer-team/visualizer-asp