name: Workflows-tests
run-name: ${{ github.actor }} is testing
on: 
    workflow_dispatch:
    workflow_call:
      secrets:
        NPM_TOKEN:
          required: true
      
jobs:

  test:
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check branch
        run: echo "echo ${GITHUB_REF##*/}"
      - name: check commit
        run : git show $GITHUB_SHA
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: check file in /home/runner/work/_temp/
        run: |
          ls -a /home/runner/work/_temp/
        # cat /home/runner/work/_temp/.npmrc
      - run: npm ci
      # - run: npm tests