name: Workflows-tests
run-name: ${{ github.actor }} is testing
on: 
    workflow_dispatch:
    workflow_call:
      secrets:
        NPM_TOKEN:
          required: true
      
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      # TO DELETE
      - uses: actions/checkout@v3
      - name: Check branch
        run: echo "echo ${GITHUB_REF##*/}"
      - name: check commit
        run : git show $GITHUB_SHA
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      # - run: |
      #     cat .cache
      #     cat .package
      #     cat .package-lock
      #     cat .npmrc

      - run: |
         npm ci
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: check .npmrc
        run: |
          cat /home/runner/.npm/_logs/2022-12-02T10_17_03_104Z-debug-0.log
        # cat ~/.npmrc
      # - run: npm tests