name: workflows-tests
run-name: ${{ github.actor }} is testing
on: 
    pull_request_target:
        types: [assigned, opened, synchronize, reopened]
    workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check branch
        run: echo "echo ${GITHUB_REF##*/}"
      - name: check commit
        run : git show $GITHUB_SHA
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: sudo apt install python3-pip
      - run: pip3 install -r requirements.txt
      - run: pytest randomness/tests/