name: Workflows-tests
run-name: ${{ github.actor }} is testing
on: 
    workflow_dispatch:
    workflow_call:
      secrets:
        NPM_TOKEN:
          required: true
      
jobs:

  test:
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: check branch
        run: echo "echo ${GITHUB_REF##*/}"
      - name: check commit
        run : git show $GITHUB_SHA
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install latest version of package
        run: |
          npm install @agile-visualizer-team/visualizer-asp@latest
          npm install
      - name: acceptance test
        run: npm run test