name: workflows-tests
run-name: ${{ github.actor }} is testing
on: 
    workflow_dispatch:
    workflow_call:
      
jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Check branch
        run: echo "echo ${GITHUB_REF##*/}"
      - name: check commit
        run : git show $GITHUB_SHA
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        env:
          NPM_AUTH_TOKEN: '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'
      # - run: npm test